### PR TITLE
Make `resample` more generic

### PR DESCRIPTION
**Pull request by jonschumacher**
I found that `resample` is currently restricted to `AbstractMatrix`, which is an alias for `AbstractArray{T,2}`. Since `mapslices` works well with `dims > 2`, the changes from #414 can easily be extended to `AbstractArray` without restrictions on dimensionality, which I did in this PR.

### CODE REVIEW

**Comment by martinholters** [comment]
Looks good on first glance, but I wonder why CI didn't run and I have no option of letting it. Can you maybe rebase and force-push?

**Comment by jonschumacher** [comment]
Thanks for the feedback. I get the following message within this PR after merging the latest changes and thereby triggering the CI again, which should be similar to a rebase and force-push without the involved risks:
grafik

The link leads to https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks, which should give the instructions to running the CI.

**Comment by rob-luke** [comment]
I've kicked the CI for you, feel free to ping if it gets stuck again.

**Review by martinholters — APPROVED** [review]
LGTM. I don't see why we shouldn't allow this.

**Comment by rob-luke** [comment]
Thanks @jonschumacher

**Pull request merged**
