### PR TITLE
Remove unused doc folder

### PR DESCRIPTION
**Pull request by galenlynch**
I think the /doc folder may be unused (see #245).

### CODE REVIEW

**Comment by galenlynch** [comment]
Looking through #182, #183, and #184, it seems like this folder in indeed obsolete. The documentation built just fine when it was removed, so I'm going to go ahead and merge this.

**Comment by martinholters** [comment]
Ref. #184 which deleted most of `doc`. Yes, I think all of this can safely be removed now. But I don't know whether anything on readthedocs should be configured/disabled before. (And if so, who has the rights to do so.)

**Comment by martinholters** [comment]
https://dspjl.readthedocs.io/en/latest/ still seems to be built from the most recent commit to master. If we can disable that, that would be good.

**Comment by martinholters** [comment]
Ah, that's unfortunate. Then the best course of actions would be to fix the link in index.rst, have the fixed page build, disable building, merge this PR. OTOH, I'm not sure how bad it would be if the readthedocs page just disappeared.

**Comment by galenlynch** [comment]
I don't think I have permissions to change the readthedocs webook. I can add the fixed link soon.

**Comment by galenlynch** [comment]
Ok I fixed the link.

**Comment by martinholters** [comment]
Great.

@ararslan, can you disable building the docs on readthedocs (e.g. by removing the integration on this repo that triggers it)?

**Comment by ararslan** [comment]
I've deactivated the ReadTheDocs integration for this repo.

**Comment by martinholters** [comment]
Thanks! Then I guess this should be good to go.

**Comment by galenlynch** [comment]
Thanks guys!

**Pull request merged**
